# Site settings
title: jjjlyn blog
url: "https://jjjlyn.github.io"
baseurl: ""
description: >
    jjjlyn blog
# My information
email: prize1142@gmail.com
author: jlyn
github_username: jjjlyn

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: jjjlyn 
  shortname: jlyn
utterances:
  repo: jjjlyn/jjjlyn.github.io
  issue-term: pathname
  label: Comment
  branch: master

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
