# Site settings
title: "jlyn's blog"
author: "jjjlyn"

baseurl: ""
url: "https://jjjlyn.github.io"

github_username: jjjlyn

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
