title: jjjlyn tech blog
description: 잊어버리지 않게 기록해두는 잡지식 창고

url: https://jjjlyn.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/
encoding: UTF-8

markdown: kramdown
highlighter: rouge
paginate: 5

# navigation:
#   - title: Posts
#     url: /index.html
#   - title: About
#     url: /about

navigation:
- title: Posts
  url: /
- title: About
  url: /about/
- title: Tags
  url: /tags/

discus_url: https://https-jjjlyn-github-io.disqus.com/
discus_id: disqus_4l6bHJqYlN

comments:
  provider : "disqus"
  disqus:
    shortname : "jjjlyn" 

social:
  github: jjjlyn
  email: prize1142@gmail.com

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true      

gems:
  - jekyll-paginate


languages: ['ko','en']
default_lang: 'ko'
exclude_from_localization: ['javascript','images','css']
parallel_localization: false
